version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db_new
    environment:  
      - POSTGRES_DB=ITIC_DB
      - POSTGRES_PASSWORD=ITIC
      - POSTGRES_USER=ITIC_user
    ports:
      - "5433:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_new
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adrian.navarro@xtec.cat
      PGADMIN_DEFAULT_PASSWORD: nava123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
